### ISSUE TITLE
Flatpak installation error on lubuntu + solution

### ISSUE THREAD

**Issue by antoninofurnari** [epic-kitchens/epic-kitchens-100-narrator#23]
Hello,

Trying to install the flatpak bundle on a fresh lubuntu installation, when receiving the error

`error: The application uk.ac.bris.epic.narrator/x86_64/master requires the runtime 
org.gnome.Platform/x86_64/3.32 which was not found`

The suggested solution, to run

`flatpak install flathub org.gnome.Sdk//3.32
flatpak install flathub org.gnome.Platform//3.32`

Did not work for me. I had to run

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

To add flathub. Then directly:

`flatpak install epic_narrator.flatpak`

Best,
Antonino

**Comment by dmoltisanti** [comment]
Thanks Antonino, the problem was indeed that the suggested solution assumes the `flathub` repo is installed, nice catch. 

By the way, I updated GTK's version from 3.32 to 3.36 since 3.32 reached EOL, thus this problem should not reappear once we upload the new bundle
